yd.clientId=0f24a76834a69e8080fd719d
yd.clientSecret=87be874f93b28a67d4ef32de2e96285e
yd.domain=https://saas-openapi.dding.net/v2
hy.clientId=A9AWitGVI+4=
hy.clientSecret=af786ef243e8695b8d7a1940da25ca3b
hy.domain=https://amr.metx.com.cn
hy.grantType=client_credentials
hs.username=cj
hs.password='!xDd!77&'
hs.typeStatus=2
hs.domain=http://lock.hanslnk.com/lockServer/