wx.hostAppId=wxe71d0468b674d1fe
wx.userAppId=wxe71d0468b674d1feU
wx.mchId=1633533417
wx.apiV3Key=DNpjpAISSJIAPSJAPSJPASJ213123123
#wx.privateCert=/usr/project/putao/wxsec/apiclient_cert.pem
#wx.privateKey=/usr/project/putao/wxsec/apiclient_key.pem
wx.privateCert=D:/key/apiclient_cert.pem
wx.privateKey=D:/key/apiclient_key.pem
#callbackurl
wx.notifyUrl=https://www.xxxx.com/billing/wx/payNotify